### ISSUE TITLE
Найти и разобраться с кодом стабилизации квадро с помощью Arduino

### ISSUE THREAD

**Issue by J-Roux** [J-Roux/project_pathfinder#12]

**Comment by J-Roux** [comment]
http://arduino-diy.com/arduino-kvadrokopter-svoimi-rukami
Пример разработки мозгов коптера

**Comment by IlyaDeineka** [comment]
Общение гироскопа/акселерометра MPU-6050 через I2C с Arduino. В примере по ссылке выше используют либу https://github.com/jrowberg/i2cdevlib/commit/05c1fde1f8e9b7ef5912a7daf4e1045841f2072d

**Comment by IlyaDeineka** [comment]
http://www.instructables.com/files/orig/FWW/XKQR/HUYLSG3S/FWWXKQRHUYLSG3S.ino
Тут код стабилизирующий положение коптера. Для работы необходима установка либы PIDLibrary: http://playground.arduino.cc/Code/PIDLibrary
Разработка системы полета опирается на приведенный код, как на код стабилизации.
