### ISSUE TITLE
Проектор сетки + камера

### ISSUE THREAD

**Issue by J-Roux** [J-Roux/project_pathfinder#6]
Найти варианты и презентовать

**Comment by J-Roux** [comment]
http://ru.aliexpress.com/item/2015-car-styling-Pattern-Anti-Collision-Rear-end-Car-Laser-Tail-12v-led-car-Fog-Light/32455329324.html

**Comment by IlyaDeineka** [comment]
https://www.youtube.com/watch?v=vIrK2Cp21BU как сделать из лазера линию. возможно на базе лазерного нивелира создать сетку

**Comment by IlyaDeineka** [comment]
а также измерение лазерным дальномером
https://www.youtube.com/watch?v=94SHhVWcnBk

**Comment by IlyaDeineka** [comment]
отказ от идеи лазерной сетки и дальномера ввиду большого энергопотребления, и наличия альтернативы без использования лазеров: https://github.com/J-Roux/project_pathfinder/issues/13
