### ISSUE TITLE
Освоение Cubieboard

### ISSUE THREAD

**Issue by J-Roux** [J-Roux/project_pathfinder#8]
Освоение платы + установка необходимого ПО. Освоение и установка Python 2.7 + scipy + numpy + scikit-learn на плату и на ноут.

**Comment by StarGrif** [comment]
Разработка тестовых программ для оценки производительности.

**Comment by IlyaDeineka** [comment]
Установлен Cubian, gcc, g++ ,python2.7

**Comment by IlyaDeineka** [comment]
Установка Wi-Fi (плата не имеет встроенного) требует танца с бубном от 666 шаманов Debian. Посему предпочтение было отдано Ethernet. Подключение к плате через SSH.
